name: Build Expo App with EAS

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: EAS Build (Android)
        run: eas build --platform android --profile production --non-interactive --wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download Build Artifacts
        run: |
          mkdir -p ./builds

          echo "Downloading Android APK..."
          eas build:download --platform android --latest --non-interactive


          # echo "Downloading iOS IPA..."
          # eas build:download --platform ios --output ./builds/bear.ipa --latest --non-interactive
          mv *.apk ./builds/bear.apk

      - name: Upload Artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./builds/*.apk
            # ./builds/*.ipa
          token: ${{ secrets.ACTION_TOKEN }}
